### PR TITLE
Fix OutOfMemoryException for large MySQL tables

### LINKED ISSUE #45: OutOfMemoryException with large MySQL table
The default options for an RS using the MySQL driver stores the entire results of a query in memory when executeQuery is called.  Unfortunately for large tables this results in an OutOfMemoryException.

### PR DESCRIPTION
**Pull request by zbateson**
The fix forces the MySQL driver into 'streaming' mode so the entire
RS isn't stored in memory.  Unfortunately in streaming mode update
queries on the same connection fail, and so a separate connection to
the database seems to be the best way around it (skipping rows also
doesn't work, and the RS cannot be updatable in streaming mode).

Fixes #45

### CODE REVIEW

File: src/main/java/com/strider/dataanonymizer/database/IDBFactory.java [hunk 1]
```diff
@@ -85,7 +99,10 @@ public void close() {
     static IDBFactory get(final Properties dbProps) throws DatabaseAnonymizerException {
         String vendor = dbProps.getProperty("vendor");
         if ("mysql".equalsIgnoreCase(vendor) || "h2".equalsIgnoreCase(vendor)) {
-            return new DBFactory() {
+            return new DBFactory(vendor) {
+                {
```
Comment (armenak) [inline src/main/java/com/strider/dataanonymizer/database/IDBFactory.java]: Codacy Issue found: [Non-static initializers are confusing](https://www.codacy.com/app/agstrider/DataDefender/file/2747939110/issues/source?bid=3319641&fileBranchId=3357101#l103)

**Comment by armenak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://www.codacy.com/app/agstrider/DataDefender/pullRequest?prid=256656&bid=3357101)

**Comment by armenak** [comment]
Merge is confirmed. Thanks, Zaahid!
